import T from './treasures'

export default [
  {
    cells: [
      { open: 'b', },
      { open: 'rb', },
      { open: 'r', },
      { open: 'r', },
      { open: 'b', },
      { open: 'rb', },
      { open: 'r', },
      { open: 'rb', },
      { open: 'rb', },
      { open: 'r', },
      { open: 'r', },
      { open: 'r', },
      { open: 'r', },
      { open: 'b', },
      { open: 'rb', },
      { open: 'r', },
      { open: 'r', },
      { open: 'b', },
      { open: 'rb', },
      { open: 'b', },

      { open: 'b', treasure: T.EARTH, },
      { open: 'b', },
      { open: 'rb', },
      { open: 'r', },
      { open: '', },
      { open: 'b', },
      { open: 'rb', },
      { open: '', },
      { open: 'r', },
      { open: 'r', },
      { open: 'r', },
      { open: 'r', },
      { open: 'b', },
      { open: 'r', },
      { open: '', },
      { open: 'rb', },
      { open: 'b', },
      { open: 'r', },
      { open: '', },
      { open: 'b', },

      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'rb', },
      { open: 'r', },
      { open: '', },
      { open: 'b', },
      { open: 'b', },
      { open: 'rb', },
      { open: 'r', },
      { open: 'r', },
      { open: 'r', },
      { open: '', },
      { open: 'rb', },
      { open: 'rb', },
      { open: '', },
      { open: 'r', },
      { open: 'b', },
      { open: 'rb', },
      { open: 'b', },

      { open: 'r', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'rb', },
      { open: 'r', },
      { open: '', },
      { open: 'b', },
      { open: 'b', },
      { open: 'rb', },
      { open: 'r', },
      { open: 'r', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'rb', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },

      { open: 'rb', },
      { open: '', },
      { open: 'b', },
      { open: 'b', },
      { open: 'rb', },
      { open: 'r', },
      { open: '', },
      { open: 'b', },
      { open: 'r', },
      { open: '', },
      { open: 'r', },
      { open: 'r', },
      { open: '', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },

      { open: 'b', },
      { open: 'b', treasure: T.FIRE, },
      { open: 'rb', },
      { open: '', },
      { open: 'r', },
      { open: 'r', },
      { open: 'rb', },
      { open: 'r', },
      { open: 'r', },
      { open: 'r', },
      { open: 'r', },
      { open: 'r', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },

      { open: 'b', },
      { open: 'b', },
      { open: 'r', },
      { open: 'r', },
      { open: '', },
      { open: 'rb', },
      { open: '', },
      { open: 'rb', },
      { open: 'b', },
      { open: 'rb', },
      { open: 'rb', },
      { open: 'rb', },
      { open: '', },
      { open: 'b', },
      { open: 'b', },
      { open: '', treasure: T.WATER, },
      { open: 'r', },
      { open: '', },
      { open: 'b', },
      { open: 'b', },

      { open: 'b', },
      { open: 'b', },
      { open: 'rb', },
      { open: 'r', },
      { open: 'r', },
      { open: '', },
      { open: 'rb', },
      { open: 'b', },
      { open: 'r', },
      { open: '', },
      { open: 'b', },
      { open: 'b', },
      { open: 'rb', },
      { open: '', },
      { open: 'r', },
      { open: 'r', },
      { open: 'b', },
      { open: 'rb', },
      { open: 'b', },
      { open: '', },

      { open: 'rb', },
      { open: '', },
      { open: 'b', },
      { open: 'rb', },
      { open: 'r', },
      { open: 'r', },
      { open: '', },
      { open: 'r', },
      { open: 'r', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'rb', },
      { open: 'r', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'r', },
      { open: 'b', },

      { open: 'b', },
      { open: 'rb', },
      { open: '', },
      { open: 'b', },
      { open: 'rb', },
      { open: 'r', },
      { open: 'r', },
      { open: 'r', },
      { open: '', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'rb', },
      { open: '', },
      { open: 'b', },
      { open: '', },
      { open: 'rb', },
      { open: 'b', },

      { open: 'b', },
      { open: 'b', },
      { open: 'rb', },
      { open: 'b', },
      { open: 'b', },
      { open: 'rb', },
      { open: 'r', },
      { open: 'b', },
      { open: 'rb', },
      { open: '', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'rb', },
      { open: 'r', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },

      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'r', },
      { open: '', },
      { open: 'b', },
      { open: 'rb', },
      { open: '', },
      { open: 'b', },
      { open: 'rb', },
      { open: '', },
      { open: 'b', },
      { open: 'b', treasure: T.WIND, },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'rb', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },

      { open: 'b', },
      { open: 'b', },
      { open: 'r', },
      { open: 'r', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'rb', },
      { open: '', },
      { open: 'b', },
      { open: 'rb', },
      { open: '', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },

      { open: 'b', },
      { open: 'r', },
      { open: 'r', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'rb', },
      { open: '', },
      { open: 'r', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'r', },
      { open: '', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },

      { open: 'r', },
      { open: 'r', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'rb', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'rb', },
      { open: 'r', },
      { open: '', },
      { open: 'b', },
      { open: 'b', },
      { open: '', },

      { open: 'rb', },
      { open: 'r', },
      { open: '', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'r', },
      { open: 'b', },
      { open: 'b', treasure: T.WIND, },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'rb', },
      { open: '', },
      { open: 'r', },
      { open: 'b', },

      { open: 'b', },
      { open: 'rb', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'r', },
      { open: 'b', },
      { open: 'r', },
      { open: '', },
      { open: 'r', },
      { open: '', },
      { open: 'b', },
      { open: 'r', },
      { open: '', },
      { open: 'r', },
      { open: 'r', },
      { open: '', },
      { open: '', },

      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'r', },
      { open: '', },
      { open: 'r', },
      { open: 'b', },
      { open: 'r', },
      { open: 'r', },
      { open: 'r', },
      { open: 'r', },
      { open: 'b', },
      { open: 'r', },
      { open: 'r', },
      { open: 'r', },
      { open: 'r', },
      { open: 'r', },
      { open: 'r', },
      { open: 'b', },

      { open: 'b', },
      { open: 'b', },
      { open: 'b', },
      { open: 'r', },
      { open: 'r', },
      { open: 'r', },
      { open: 'b', },
      { open: 'r', },
      { open: 'r', },
      { open: 'r', },
      { open: 'r', },
      { open: 'b', },
      { open: 'r', },
      { open: 'r', },
      { open: 'r', },
      { open: 'r', },
      { open: '', },
      { open: 'rb', },
      { open: 'b', },
      { open: 'b', },

      { open: 'r', },
      { open: '', },
      { open: 'r', },
      { open: 'r', },
      { open: 'r', },
      { open: '', treasure: T.TAICHI, },
      { open: 'r', },
      { open: 'r', },
      { open: 'r', },
      { open: 'r', },
      { open: '', },
      { open: 'r', },
      { open: 'r', },
      { open: 'r', },
      { open: 'r', },
      { open: 'r', },
      { open: 'r', },
      { open: '', },
      { open: '', },
      { open: '', treasure: T.HEAVEN, },
    ],
    hints: [
      0, 20, 40, 60, 61, 41, 21, 1, 2, 3, 4, 24, 23, 22, 42, 62, 82, 102, 103,
      83, 63, 43, 44, 45, 25, 5, 6, 7, 27, 26, 46, 66, 65, 64, 84, 104, 105,
      106, 107, 108, 109, 110, 111, 112, 132, 131, 151, 171, 191, 211, 231,
      251, 250, 270, 271, 291, 311, 331, 332, 312, 292, 272, 252, 232, 212,
      192, 172, 152, 153, 133, 113, 93, 73, 53, 54, 74, 94, 114, 134, 154, 155,
      156, 176, 196, 216, 215, 235, 255, 275, 274, 254, 234, 214, 194, 195,
      175, 174, 173, 193, 213, 233, 253, 273, 293, 313, 333, 353, 354, 355,
      356, 357, 358, 359, 379, 399
    ],
  }
]
